### ISSUE TITLE
FailedPreconditionError with Pretty tensor tutorial 3

### ISSUE THREAD

**Issue by ibadami** [Hvass-Labs/TensorFlow-Tutorials#9]
Hi,

When running your tutorial 3 on pretty tensor, I get `FailedPreconditionError`.  I am using tensorflow_gpu-0.12.0rc0-cp27-none-linux_x86_64 and prettytensor-0.6.2 with python2.7. The error occurs at the first print_test_accuracy() call.

When I searched on internet, I see that this error can occur if the session variables are not initialized.
In your tutorial they are initialized. Moreover I haven't received this error with first two tutorials. 

I am wondering if this has something to do with prettytensor variables. Below is the trace back error message. 

```
Use `tf.global_variables_initializer` instead.
Traceback (most recent call last):
  File "train.py", line 139, in <module>
    print_test_accuracy(dataset.data)
  File "train.py", line 88, in print_test_accuracy
    cls_pred[i:j] = session.run(y_pred_cls, feed_dict=feed_dict)
  File "/home/badami/Codes/deeplearning/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 766, in run
    run_metadata_ptr)
  File "/home/badami/Codes/deeplearning/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 964, in _run
    feed_dict_string, options, run_metadata)
  File "/home/badami/Codes/deeplearning/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1014, in _do_run
    target_list, options, run_metadata)
  File "/home/badami/Codes/deeplearning/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1034, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.FailedPreconditionError: Attempting to use uninitialized value layer_conv1/weights
	 [[Node: layer_conv1/weights/read = Identity[T=DT_FLOAT, _class=["loc:@layer_conv1/weights"], _device="/job:localhost/replica:0/task:0/cpu:0"](layer_conv1/weights)]]

Caused by op u'layer_conv1/weights/read', defined at:
  File "train.py", line 4, in <module>
    from debug import *
  File "/home/badami/Codes/deeplearning/src/debug.py", line 4, in <module>
    from param import *
  File "/home/badami/Codes/deeplearning/src/param.py", line 14, in <module>
    y_pred, loss = model1(x_image, y_true)
  File "/home/badami/Codes/deeplearning/src/models.py", line 11, in model1
    conv2d(kernel=5, depth=16, name='layer_conv1').\
  File "/home/badami/Codes/deeplearning/tensorflow/local/lib/python2.7/site-packages/prettytensor/pretty_tensor_class.py", line 1981, in method
    result = func(non_seq_layer, *args, **kwargs)
  File "/home/badami/Codes/deeplearning/tensorflow/local/lib/python2.7/site-packages/prettytensor/pretty_tensor_image_methods.py", line 159, in __call__
    params = self.variable('weights', size, init, dt=dtype)
  File "/home/badami/Codes/deeplearning/tensorflow/local/lib/python2.7/site-packages/prettytensor/pretty_tensor_class.py", line 1695, in variable
    collections=variable_collections)
  File "/home/badami/Codes/deeplearning/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 1024, in get_variable
    custom_getter=custom_getter)
  File "/home/badami/Codes/deeplearning/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 850, in get_variable
    custom_getter=custom_getter)
  File "/home/badami/Codes/deeplearning/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 346, in get_variable
    validate_shape=validate_shape)
  File "/home/badami/Codes/deeplearning/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 331, in _true_getter
    caching_device=caching_device, validate_shape=validate_shape)
  File "/home/badami/Codes/deeplearning/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 677, in _get_single_variable
    expected_shape=shape)
  File "/home/badami/Codes/deeplearning/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/ops/variables.py", line 224, in __init__
    expected_shape=expected_shape)
  File "/home/badami/Codes/deeplearning/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/ops/variables.py", line 370, in _init_from_args
    self._snapshot = array_ops.identity(self._variable, name="read")
  File "/home/badami/Codes/deeplearning/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/ops/gen_array_ops.py", line 1424, in identity
    result = _op_def_lib.apply_op("Identity", input=input, name=name)
  File "/home/badami/Codes/deeplearning/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 759, in apply_op
    op_def=op_def)
  File "/home/badami/Codes/deeplearning/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2240, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/home/badami/Codes/deeplearning/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1128, in __init__
    self._traceback = _extract_stack()

FailedPreconditionError (see above for traceback): Attempting to use uninitialized value layer_conv1/weights
	 [[Node: layer_conv1/weights/read = Identity[T=DT_FLOAT, _class=["loc:@layer_conv1/weights"], _device="/job:localhost/replica:0/task:0/cpu:0"](layer_conv1/weights)]]
```

**Comment by ckchng** [comment]
I encountered the exact same issue too.

**Comment by Hvass-Labs** [comment]
You're way ahead of me :-) I haven't tried TensorFlow 0.12 yet and I just got my GPU laptop yesterday. It'll be a while before I have it setup on that PC.

However, these tutorials were developed with Python 3.5 and sometimes 2.7 gives strange error-messages. Please try using Python 3.5 and see if that fixes the issue?

Another thing you could try is to replace the following two lines:


    session = tf.Session()
    session.run(tf.initialize_all_variables())

with something like this:

    init_op = tf.initialize_all_variables()
    session = tf.Session()
    session.run(init_op)

Does that fix the issue?

You can also try running TensorFlow 0.11.

I hope you can find the solution and report back so I can fix it in the Notebook.

Cheers!

**Comment by ibadami** [comment]
Thanks for the prompt reply. 
I have checked the following things right after I had posted the issue.
Python 3.4 -> same issue.
changed the lines of session as described by you with python 2.7 (the same solution I found from other thread as well) -> not working.
Run another pretty tensor [tutorial](https://github.com/google/prettytensor/blob/master/prettytensor/tutorial/mnist.py) on MNIST provided on pretty tensor github page with python 2.7, python 3.4 -> same error.
I have raised an [issue](https://github.com/google/prettytensor/issues/38) on prettytensor github repo as well.
I am having a strong feeling that the problem is with pretty tensor/tensorflow library and not with your tutorial.
Thank you once again. Very informative tutorials and videos. 
Cheers!

**Comment by ckchng** [comment]
Hi, I've managed to solve this problem by updating my pretty tensor to the latest version as pointed out in your [issue](https://github.com/google/prettytensor/issues/38).

**Comment by ibadami** [comment]
yes that was version mismatch between tensorflow and pretty tensor. I solved it too. works with both python 2.7 and 3.4.

**Comment by Hvass-Labs** [comment]
Thanks for investigating the issue and sharing the solution.

**Comment by deamonDevs** [comment]
how i make our own data set for im2txt model...
